import { Injectable } from '@nestjs/common';
import { CreatePatientDto } from './dto/create-patient.dto';
import { UpdatePatientDto } from './dto/update-patient.dto';
import { PrismaService } from '../prisma/prisma.service';
import { NotificationDispatcherService } from '../messaging/notification-dispatcher.service';
import { AlignerService } from './aligner.service';
import { Prisma, MessageTemplateType, MessageChannel } from '@prisma/client';

@Injectable()
export class PatientsService {
  constructor(
    private prisma: PrismaService,
    private notificationDispatcher: NotificationDispatcherService,
    private alignerService: AlignerService,
  ) {}

  // This method now needs to be async to handle the message sending
  async create(createPatientDto: CreatePatientDto, userId: string) {
    let batchStartDateObj: Date | undefined = undefined;
    if (createPatientDto.batchStartDate) {
      batchStartDateObj = new Date(createPatientDto.batchStartDate + 'T00:00:00');
    }

    // Step 1: Create the patient in the database first
    const newPatient = await this.prisma.patient.create({
      data: {
        ...createPatientDto,
        userId: userId,
        // This forces the date to be interpreted as UTC midnight to prevent timezone bugs
        treatmentStartDate: new Date(
          createPatientDto.treatmentStartDate + 'T00:00:00',
        ),
        batchStartDate: batchStartDateObj,
        onboardingToken: {
          create: {
            // token will be auto-generated by the db default(cuid)
            expiresAt: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000), // 30 days
          },
        },
        alignerBatches: (createPatientDto.totalAligners || 0) > 0 ? {
          create: [{
            status: 'NEEDED',
            alignerCount: createPatientDto.totalAligners,
            createdBy: userId,
            batchEvents: {
              create: [{
                toStatus: 'NEEDED',
                note: 'Initial batch created automatically',
                createdBy: userId,
              }]
            }
          }]
        } : undefined,
      },
      include: {
        onboardingToken: true,
      }
    });

    // Step 2: After the patient is successfully created, try to send a welcome message via EMAIL
    try {
      // 1. Find the WELCOME template for EMAIL channel
      const welcomeTemplate = await this.prisma.messageTemplate.findFirst({
        where: { type: MessageTemplateType.WELCOME, channel: MessageChannel.EMAIL, isActive: true }
      });

      if (welcomeTemplate && newPatient.email) {
        // 2. Dispatch it via Resend (email)
        await this.notificationDispatcher.dispatch({
          patientId: newPatient.id,
          templateType: MessageTemplateType.WELCOME,
          template: welcomeTemplate,
          channel: MessageChannel.EMAIL,
          recipient: newPatient.email,
          variables: {
            patient_name: newPatient.fullName.split(' ')[0],
            clinic_name: 'Alnix'
          },
          triggeredBy: 'manual',
          subject: `¡Bienvenido/a a Alnix, ${newPatient.fullName.split(' ')[0]}!`,
        });
      }
    } catch (error) {
      console.error(
        `Patient ${newPatient.fullName} was created, but the welcome email failed to send.`,
        error,
      );
    }

    // Step 3: Return the data for the newly created patient
    return this.mapPatientWithUrgency(newPatient);
  }

  async checkDuplicates(rut?: string, email?: string, phone?: string, userId?: string, excludePatientId?: string) {
    if (!userId) return { exists: false, conflicts: [] };
    
    // Build the OR conditions based on provided fields
    const orConditions: any[] = [];
    if (rut) orConditions.push({ rut });
    if (email) orConditions.push({ email });
    if (phone) orConditions.push({ phone });

    // If no fields to check, return false
    if (orConditions.length === 0) return { exists: false, conflicts: [] };

    const whereClause: any = {
      userId,
      OR: orConditions
    };

    // If we are editing, we don't want to flag the patient themselves as a duplicate
    if (excludePatientId) {
      whereClause.id = { not: excludePatientId };
    }

    const existingPatient = await this.prisma.patient.findFirst({
      where: whereClause
    });

    if (!existingPatient) {
      return { exists: false, conflicts: [] };
    }

    // Determine which exact fields conflicted to tell the user
    const conflicts: string[] = [];
    if (rut && existingPatient.rut === rut) conflicts.push('RUT');
    if (email && existingPatient.email === email) conflicts.push('Email');
    if (phone && existingPatient.phone === phone) conflicts.push('Phone');

    return { exists: true, conflicts };
  }

  // The method now needs to accept page and limit, with defaults
  async findAll(page: number = 1, limit: number = 10) {
    const skip = (page - 1) * limit; // Calculate how many records to skip

    // We now run two queries: one for the data, one for the total count
    const [patients, total] = await this.prisma.$transaction([
      this.prisma.patient.findMany({
        skip: skip,
        take: limit,
        orderBy: { createdAt: 'desc' }, // Always good to have a consistent order
        include: {
          onboardingToken: true,
          alignerBatches: {
            where: { status: { notIn: ['DELIVERED_TO_CLINIC', 'HANDED_TO_PATIENT', 'CANCELLED'] } },
            orderBy: { createdAt: 'desc' },
            take: 1,
          },
          reevaluations: {
            where: { status: { in: ['NEEDED', 'SCAN_UPLOADED'] } },
            orderBy: { createdAt: 'desc' },
            take: 1,
          }
        }
      }),
      this.prisma.patient.count(),
    ]);

    return {
      data: patients.map(p => this.mapPatientWithUrgency(p)),
      total,
      page,
      limit,
      totalPages: Math.ceil(total / limit),
    };
  }

  async findOne(id: string) {
    const patient = await this.prisma.patient.findUnique({
      where: { id: id },
      include: {
        onboardingToken: true,
        clinicalRecords: true,
        patientImages: true,
        alignerBatches: {
          where: { status: { notIn: ['DELIVERED_TO_CLINIC', 'HANDED_TO_PATIENT', 'CANCELLED'] } },
          orderBy: { createdAt: 'desc' },
          take: 1,
        },
        reevaluations: {
          where: { status: { in: ['NEEDED', 'SCAN_UPLOADED'] } },
          orderBy: { createdAt: 'desc' },
          take: 1,
        }
      },
    });
    return patient ? this.mapPatientWithUrgency(patient) : null;
  }

  // Note: The update method could also be modified to handle dates correctly if needed
  async update(id: string, updatePatientDto: UpdatePatientDto) {
    // 2. Create a correctly typed data object
    const dataToUpdate: Prisma.PatientUpdateInput = {
      ...updatePatientDto,
    };

    // 3. The 'if' check remains the same
    if (updatePatientDto.treatmentStartDate) {
      dataToUpdate.treatmentStartDate = new Date(
        updatePatientDto.treatmentStartDate + 'T00:00:00',
      );
    }

    if (updatePatientDto.batchStartDate) {
      dataToUpdate.batchStartDate = new Date(
        updatePatientDto.batchStartDate + 'T00:00:00',
      );
    }

    const updated = await this.prisma.patient.update({
      where: { id },
      data: dataToUpdate, // 4. Now this assignment is safe!
    });
    
    return this.mapPatientWithUrgency(updated);
  }

  remove(id: string) {
    return this.prisma.patient.delete({
      where: { id },
    });
  }

  /**
   * @deprecated Use startTreatment() instead.
   * Kept for backward compatibility — redirects to startTreatment with aligner=1 and today's date.
   */
  async startTracking(id: string, userId: string) {
    const patient = await this.prisma.patient.findUnique({ where: { id } });
    if (!patient || patient.userId !== userId) {
      throw new Error('Patient not found or unauthorized');
    }

    const startingAligner = patient.currentAligner > 0 ? patient.currentAligner : 1;
    return this.startTreatment(id, startingAligner, new Date().toISOString().split('T')[0], userId);
  }

  /**
   * startTreatment: Initializes (or re-initializes) aligner tracking with a
   * specific starting aligner number and date. Replaces the simpler
   * startTracking for cases where the patient is already mid-treatment.
   */
  async startTreatment(
    id: string,
    startingAligner: number,
    startDate: string,
    userId: string,
    wearDaysPerAligner?: number,
    totalAligners?: number,
  ) {
    const patient = await this.prisma.patient.findUnique({ where: { id } });
    if (!patient || patient.userId !== userId) {
      throw new Error('Patient not found or unauthorized');
    }

    const parsedDate = new Date(startDate + 'T00:00:00');
    const effectiveWearDays = wearDaysPerAligner ?? patient.wearDaysPerAligner ?? 14;

    // First update treatment-level fields (dates, wear days, total aligners)
    await this.prisma.patient.update({
      where: { id },
      data: {
        trackingStartedAt: parsedDate,
        treatmentStartDate: parsedDate,
        lastAppointmentDate: parsedDate,
        ...(wearDaysPerAligner !== undefined && { wearDaysPerAligner }),
        ...(totalAligners !== undefined && { totalAligners }),
      },
    });

    // If the start date is in the past, fast-forward currentAligner to where
    // the patient actually is today based on elapsed wear periods.
    // e.g. started April 8 with aligner 1, 10 days/aligner, today is May 1:
    //   → 23 days elapsed → 2 full periods → actualAligner = 1 + 2 = 3
    //   → anchor (lastAlignerSetAt) = April 8 + 20 days = April 28
    const today = new Date();
    today.setHours(0, 0, 0, 0);
    const msPerDay = 24 * 60 * 60 * 1000;
    const daysSinceStart = Math.max(0, Math.floor((today.getTime() - parsedDate.getTime()) / msPerDay));
    const stepsElapsed = Math.floor(daysSinceStart / effectiveWearDays);
    const actualCurrentAligner = startingAligner + stepsElapsed;

    // The anchor is the date when the *current* aligner started being worn
    const anchorDate = stepsElapsed > 0
      ? new Date(parsedDate.getTime() + stepsElapsed * effectiveWearDays * msPerDay)
      : parsedDate;

    // Set through the single write path (handles clamping + audit record)
    const updated = await this.alignerService.setCurrentAligner(
      id,
      actualCurrentAligner,
      anchorDate,
      'manual_start',
    );

    return this.mapPatientWithUrgency(updated);
  }

  /**
   * setPipelineOverride: Manually fixes the patient into a specific pipeline
   * stage. Pass null to restore automatic calculation.
   */
  async setPipelineOverride(id: string, stage: string | null) {
    const VALID_STAGES = [
      'REQUIRED_FILES',
      'IN_PRODUCTION',
      'READY_FOR_PICKUP',
      'IN_TREATMENT',
      'ENDING_SOON',
      'REEVALUATION',
    ];

    if (stage !== null && !VALID_STAGES.includes(stage)) {
      throw new Error(`Invalid pipeline stage: ${stage}`);
    }

    const updated = await this.prisma.patient.update({
      where: { id },
      data: { pipelineOverride: stage },
    });

    return this.mapPatientWithUrgency(updated);
  }

  async adjustAligner(id: string, alignerNumber: number) {
    // Route through the single write path — resets the cron anchor to today
    const updated = await this.alignerService.setCurrentAligner(
      id,
      alignerNumber,
      new Date(),
      'manual_adjustment',
    );
    return this.mapPatientWithUrgency(updated);
  }

  async setLastAppointment(id: string, date: string) {
    const updated = await this.prisma.patient.update({
      where: { id },
      data: { lastAppointmentDate: new Date(date + 'T00:00:00') },
    });

    return this.mapPatientWithUrgency(updated);
  }

  async getStats() {
    const total = await this.prisma.patient.count();
    const active = await this.prisma.patient.count({
      where: { status: 'ACTIVE' },
    });
    const paused = await this.prisma.patient.count({
      where: { status: 'PAUSED' },
    });
    const finished = await this.prisma.patient.count({
      where: { status: 'FINISHED' },
    });

    return { total, active, paused, finished };
  }

  async getPipeline() {
    const activePatients = await this.prisma.patient.findMany({
      where: { status: 'ACTIVE' },
      include: {
        onboardingToken: true,
        alignerBatches: {
          where: { status: { notIn: ['HANDED_TO_PATIENT', 'CANCELLED'] } },
          orderBy: { createdAt: 'desc' },
          take: 1,
        },
        reevaluations: {
          where: { status: { in: ['NEEDED', 'SCAN_UPLOADED'] } },
          orderBy: { createdAt: 'desc' },
          take: 1,
        }
      }
    });

    const mappedPatients = activePatients.map(p => this.mapPatientWithUrgency(p));
    
    // Group patients by pipelineStage
    const pipeline = {
      REQUIRED_FILES: [] as any[],
      IN_PRODUCTION: [] as any[],
      READY_FOR_PICKUP: [] as any[],
      IN_TREATMENT: [] as any[],
      ENDING_SOON: [] as any[],
      REEVALUATION: [] as any[],
    };

    mappedPatients.forEach(patient => {
      if (patient.pipelineStage && pipeline[patient.pipelineStage as keyof typeof pipeline]) {
        pipeline[patient.pipelineStage as keyof typeof pipeline].push(patient);
      }
    });

    return pipeline;
  }

  async findUpcomingChanges(page: number = 1, limit: number = 5) {
    const activePatients = await this.prisma.patient.findMany({
      where: { status: 'ACTIVE' },
      include: {
        alignerBatches: {
          where: { status: { notIn: ['DELIVERED_TO_CLINIC', 'HANDED_TO_PATIENT', 'CANCELLED'] } },
          orderBy: { createdAt: 'desc' },
          take: 1,
        },
        reevaluations: {
          where: { status: { in: ['NEEDED', 'SCAN_UPLOADED'] } },
          orderBy: { createdAt: 'desc' },
          take: 1,
        }
      }
    });

    const today = new Date();
    today.setHours(0, 0, 0, 0);

    const patientsWithNextChange = activePatients.map((patient) => {
      const startDate = new Date(patient.treatmentStartDate);
      const timeDiff = today.getTime() - startDate.getTime();
      const daysSinceStart = Math.floor(timeDiff / (1000 * 3600 * 24));

      const remainder =
        daysSinceStart >= 0 ? daysSinceStart % patient.changeFrequency : 0;
      // If remainder is 0 and treatment has started, today IS a change day
      const daysUntilNextChange = (daysSinceStart > 0 && remainder === 0)
        ? 0
        : patient.changeFrequency - remainder;

      const nextChangeDate = new Date(today);
      nextChangeDate.setDate(today.getDate() + daysUntilNextChange);

      const currentAligner = patient.currentAligner || 1;

      return {
        id: patient.id,
        fullName: patient.fullName,
        daysUntilNextChange,
        nextChangeDate,
        currentAligner,
      };
    });

    // Sort patients by who is closest to their next change
    const sortedPatients = patientsWithNextChange.sort(
      (a, b) => a.daysUntilNextChange - b.daysUntilNextChange,
    );

    // Manually apply pagination to the sorted array
    const startIndex = (page - 1) * limit;
    const endIndex = page * limit;
    const paginatedData = sortedPatients.slice(startIndex, endIndex);

    return {
      data: paginatedData,
      total: sortedPatients.length,
      page,
      limit,
      totalPages: Math.ceil(sortedPatients.length / limit),
    };
  }
  async uploadAvatar(id: string, url: string) {
    return this.prisma.patient.update({
      where: { id },
      data: { avatarUrl: url },
    });
  }

  async searchPatients(query: string, userId: string) {
    if (!query || query.trim().length === 0) return [];

    const patients = await this.prisma.patient.findMany({
      where: {
        userId,
        fullName: { contains: query, mode: 'insensitive' },
      },
      take: 8,
      orderBy: { fullName: 'asc' },
      include: {
        alignerBatches: {
          where: { status: { notIn: ['DELIVERED_TO_CLINIC', 'HANDED_TO_PATIENT', 'CANCELLED'] } },
          orderBy: { createdAt: 'desc' },
          take: 1,
        },
        reevaluations: {
          where: { status: { in: ['NEEDED', 'SCAN_UPLOADED'] } },
          orderBy: { createdAt: 'desc' },
          take: 1,
        },
      },
    });

    return patients.map(p => {
      const mapped = this.mapPatientWithUrgency(p);
      return {
        id: mapped.id,
        fullName: mapped.fullName,
        currentAligner: mapped.currentAligner,
        totalAligners: mapped.totalAligners,
        status: mapped.status,
        avatarUrl: mapped.avatarUrl,
        pipelineStage: mapped.pipelineStage,
      };
    });
  }

  // Helper method to compute urgencyStatus and append to patient objects
  private mapPatientWithUrgency(patient: any) {
    if (!patient) return null;
    
    let urgencyStatus = 'ON_TRACK';
    if (!patient.totalAligners || patient.totalAligners === 0) {
      urgencyStatus = 'AWAITING_REEVALUATION';
    } else if (patient.trackingStartedAt && patient.wearDaysPerAligner) {
      const expectedEndDate = new Date(patient.trackingStartedAt);
      expectedEndDate.setDate(expectedEndDate.getDate() + (patient.totalAligners * patient.wearDaysPerAligner));
      
      const today = new Date();
      today.setHours(0, 0, 0, 0);
      
      const diffTime = expectedEndDate.getTime() - today.getTime();
      const diffDays = Math.ceil(diffTime / (1000 * 3600 * 24));
      
      if (diffDays < 0) {
        urgencyStatus = 'OVERDUE';
      } else if (diffDays <= 14) {
        urgencyStatus = 'ENDING_SOON';
      }
    } else {
       urgencyStatus = 'ON_TRACK'; 
    }

    let pipelineStage: string | null = null;
    const activeBatch = patient.alignerBatches?.[0];
    const activeReeval = patient.reevaluations?.[0];

    // Priority 0: Manual override — doctor explicitly set a stage
    if (patient.pipelineOverride) {
      pipelineStage = patient.pipelineOverride;
    }
    // Priority 1: Active Re-evaluation
    else if (activeReeval) {
      pipelineStage = 'REEVALUATION';
    } 
    // Priority 2: Pending/Active Batch
    else if (activeBatch) {
      if (activeBatch.status === 'NEEDED') {
        pipelineStage = 'REQUIRED_FILES';
      } else if (activeBatch.status === 'ORDER_SENT' || activeBatch.status === 'IN_PRODUCTION') {
        pipelineStage = 'IN_PRODUCTION';
      } else if (activeBatch.status === 'DELIVERED_TO_CLINIC') {
        pipelineStage = 'READY_FOR_PICKUP';
      } else if (activeBatch.status === 'HANDED_TO_PATIENT') {
        if (urgencyStatus === 'ENDING_SOON' || urgencyStatus === 'OVERDUE') {
          pipelineStage = 'ENDING_SOON';
        } else {
          pipelineStage = 'IN_TREATMENT';
        }
      }
    } 
    // Priority 3: Ending Soon (derived from Urgency)
    else if (urgencyStatus === 'ENDING_SOON' || urgencyStatus === 'OVERDUE') {
      pipelineStage = 'ENDING_SOON';
    }
    // Fallback: Assigned to REQUIRED_FILES
    else {
      pipelineStage = 'REQUIRED_FILES';
    }

    return {
      ...patient,
      urgencyStatus,
      pipelineStage,
      pipelineIsManual: !!patient.pipelineOverride,
    };
  }
}
